/**
 * Acceso Inteligente
 *
 * Copyright (C) 2010-2011 Fundación Ciudadano Inteligente
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package org.accesointeligente.shared;

public enum InstitutionClass {
	AgenciaDeCooperacionInternacional,
	ArmadaDeChile,
	CajaDePrevisionDeLaDefensaNacional,
	ComisionAdministradoraDelSistemaDeCreditosParaEstudiosSuperiores,
	ComisionChilenaDeEnergiaNuclear,
	ComisionChilenaDelCobre,
	ComisionNacionalDeEnergia,
	ComisionNacionalDeInvestigacionEnCienciaYTecnologia,
	ComisionNacionalDeRiego,
	ComiteDeInversionesExtranjeras,
	ConsejoDeDefensaDelEstado,
	ConsejoDeRectoresDeLasUniversidadesChilenas,
	ConsejoNacionalDeAcreditacion,
	ConsejoNacionalDeLaCulturaYLasArtes,
	ConsejoNacionalDeTelevision,
	CorporacionDeAsistenciaJudicialRegionBiobio,
	CorporacionDeAsistenciaJudicialRegionesTarapacaYAntofagasta,
	CorporacionDeAsistenciaJudicialRegionMetropolitana,
	CorporacionDeAsistenciaJudicialRegionValparaiso,
	CorporacionNacionalDeDesarrolloIndigena,
	CorporacionNacionalForestal,
	DefensaCivilDeChile,
	DefensoriaPenalPublica,
	DireccionAdministrativa,
	DireccionDeComprasYContratacionPublica,
	DireccionDelTrabajo,
	DireccionDePresupuestos,
	DireccionDePrevisionDeCarabinerosDeChile,
	DireccionGeneralDeAeronauticaCivil,
	DireccionGeneralDeCreditoPrendario,
	DireccionGeneralDelTerritorioMaritimoYMarinaMercante,
	DireccionGeneralDeMovilizacionNacional,
	DireccionGeneralDeRelacionesEconomicasInternacionales,
	DireccionNacionalDeFronterasYLimitesDelEstado,
	DireccionNacionalDelServicioCivil,
	EjercitoDeChile,
	FiscaliaNacionalEconomica,
	FondoDeSolidaridadEInversionSocial,
	FondoNacionalDeSalud,
	FuerzaAereaDeChile,
	GendarmeriaDeChile,
	GobiernoRegionalDeAntofagasta,
	GobiernoRegionalDeAricaYParinacota,
	GobiernoRegionalDeAtacama,
	GobiernoRegionalDeAysen,
	GobiernoRegionalDeCoquimbo,
	GobiernoRegionalDeLaAraucania,
	GobiernoRegionalDelBiobio,
	GobiernoRegionalDelMaule,
	GobiernoRegionalDeLosLagos,
	GobiernoRegionalDeLosRios,
	GobiernoRegionalDeMagallanesYAntarticaChilena,
	GobiernoRegionalDeOHiggins,
	GobiernoRegionalDeTarapaca,
	GobiernoRegionalDeValparaiso,
	InstitutoAntarticoChileno,
	InstitutoDePrevisionSocial,
	InstitutoDeSeguridadLaboral,
	InstitutoGeograficoMilitar,
	InstitutoNacionalDeLaJuventud,
	InstitutoNacionalDelDeporte,
	InstitutoNacionalDePropiedadIntelectual,
	JuntaDeAeronauticaCivil,
	JuntaNacionalDeAuxilioEscolarYBecas,
	JuntaNacionalDeJardinesInfantiles,
	OficinaNacionalDeEmergencia,
	OficinasDeEstudiosYPoliticasAgrarias,
	PoliciaDeInvestigaciones,
	PresidenciaDeLaRepublica,
	ServicioAerofotogrametricoFach,
	ServicioAgricolaYGanadero,
	ServicioDeSaludArauco,
	ServicioDeSaludAtacama,
	ServicioDeSaludAysen,
	ServicioDeSaludCoquimbo,
	ServicioDeSaludDeChiloe,
	ServicioDeSaludDelReloncavi,
	ServicioDeSaludMagallanes,
	ServicioDeSaludOhiggins,
	ServicioDeSaludOsorno,
	ServicioHidrograficoYOceanograficoDeLaArmada,
	ServicioNacionalDeAduanas,
	ServicioNacionalDeGeologiaYMineria,
	ServicioNacionalDelAdultoMayor,
	ServicioNacionalDeLaMujer,
	ServicioNacionalDelConsumidor,
	ServicioNacionalDeMenores,
	ServicioNacionalDePesca,
	ServicioNacionalDeTurismo,
	SubsecretariaDeAgricultura,
	SubsecretariaDeAviacion,
	SubsecretariaDeBienesNacionales,
	SubsecretariaDeCarabineros,
	SubsecretariaDeDesarrolloRegional,
	SubsecretariaDeEconomia,
	SubsecretariaDeGuerra,
	SubsecretariaDeInvestigaciones,
	SubsecretariaDeJusticia,
	SubsecretariaDelTrabajo,
	SubsecretariaDeMarina,
	SubsecretariaDeMineria,
	SubsecretariaDePesca,
	SubsecretariaDePlanificacionYCooperacion,
	SubsecretariaDePrevisionSocial,
	SubsecretariaDeRelacionesExteriores,
	SubsecretariaDeTelecomunicaciones,
	SubsecretariaDeTransporte,
	SuperintendenciaDeBancosEInstitucionesFinancieras,
	SuperintendenciaDeCasinosDeJuego,
	SuperintendenciaDeElectricidadYCombustibles,
	SuperintendenciaDePensiones,
	SuperintendenciaDeQuiebras
}
